apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=postgresql-postgresql.primary.svc.cluster.local user=postgres password=supersecurepassword port=5432 database=postgres sslmode=disable"
  - name: actorStateStore
    value: "true"