{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  database_url: {{ printf "postgresql://%s:%s@%s-postgres-service:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "todo-app.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  secret_key: {{ .Values.backend.env.SECRET_KEY | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.backend.env.ADMIN_PASSWORD | b64enc | quote }}
{{- end }}

{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}